export const SEED_DATA = [
  {
    id: "1",
    title: "Foundation & Architecture",
    description: "Setting up the bedrock of the CRM: Database schemas, Authentication, and basic UI shell.",
    status: "Completed",
    iconName: "LuDatabase",
    deliverables: [
      { id: "1-1", text: "Database Schema Design", status: "Completed", startDate: "2025-01-15", durationDays: 15 },
      { id: "1-2", text: "Authentication System", status: "Completed", startDate: "2025-01-30", durationDays: 15 },
      { id: "1-3", text: "Basic UI Shell", status: "Completed", startDate: "2025-02-14", durationDays: 15 },
      { id: "1-4", text: "API Architecture", status: "Completed", startDate: "2025-03-01", durationDays: 15 },
    ],
  },
  {
    id: "2",
    title: "Contact & Lead Management",
    description: "Building the core CRM entities: Contacts, Companies, Deals, and Pipelines.",
    status: "Implementing",
    iconName: "LuUsers",
    deliverables: [
      { id: "2-1", text: "Contact 360 View", status: "Completed", startDate: "2025-03-15", durationDays: 7 },
      { id: "2-2", text: "Kanban Deal Pipelines", status: "Implementing", startDate: "2025-03-22", durationDays: 8 },
      { id: "2-3", text: "Activity Logging (Calls/Notes)", status: "Planning & Research", startDate: "2025-03-30", durationDays: 7 },
      { id: "2-4", text: "Import/Export Engines", status: "Not Started", startDate: "2025-04-06", durationDays: 8 },
    ],
  },
  {
    id: "3",
    title: "Social Media Aggregation",
    description: "Integrating APIs from LinkedIn, X (Twitter), Instagram, and Facebook for unified inbox and posting.",
    status: "Not Started",
    iconName: "LuShare2",
    deliverables: [
      { id: "3-1", text: "LinkedIn API Integration", status: "Not Started", startDate: "2025-04-15", durationDays: 10 },
      { id: "3-2", text: "X (Twitter) API Integration", status: "Not Started", startDate: "2025-04-25", durationDays: 10 },
      { id: "3-3", text: "Instagram API Integration", status: "Not Started", startDate: "2025-05-05", durationDays: 10 },
      { id: "3-4", text: "Unified Inbox", status: "Not Started", startDate: "2025-05-15", durationDays: 15 },
    ],
  },
  {
    id: "4",
    title: "Content Scheduler & Publisher",
    description: "The visual calendar for planning, drafting, and scheduling posts across all channels.",
    status: "Not Started",
    iconName: "LuCalendar",
    deliverables: [
      { id: "4-1", text: "Visual Calendar", status: "Not Started", startDate: "2025-06-01", durationDays: 10 },
      { id: "4-2", text: "Post Drafting", status: "Not Started", startDate: "2025-06-11", durationDays: 10 },
      { id: "4-3", text: "Multi-channel Scheduling", status: "Not Started", startDate: "2025-06-21", durationDays: 10 },
    ],
  },
  {
    id: "5",
    title: "Analytics & ROI Dashboard",
    description: "Tracking performance: Engagement rates, lead conversion from social, and team productivity.",
    status: "Planning & Research",
    iconName: "LuBarChart",
    deliverables: [
      { id: "5-1", text: "Engagement Metrics", status: "Planning & Research", startDate: "2025-07-01", durationDays: 10 },
      { id: "5-2", text: "Lead Conversion Tracking", status: "Not Started", startDate: "2025-07-11", durationDays: 10 },
      { id: "5-3", text: "Team Productivity Reports", status: "Not Started", startDate: "2025-07-21", durationDays: 10 },
    ],
  },
  {
    id: "6",
    title: "Beta Launch & Optimization",
    description: "Closed beta testing, bug squashing, performance tuning, and final public release.",
    status: "Not Started",
    iconName: "LuRocket",
    deliverables: [
      { id: "6-1", text: "Closed Beta Testing", status: "Not Started", startDate: "2025-08-01", durationDays: 7 },
      { id: "6-2", text: "Bug Fixes", status: "Not Started", startDate: "2025-08-08", durationDays: 8 },
      { id: "6-3", text: "Performance Optimization", status: "Not Started", startDate: "2025-08-16", durationDays: 7 },
      { id: "6-4", text: "Public Release", status: "Not Started", startDate: "2025-08-23", durationDays: 8 },
    ],
  },
];
